-- CloudBase PostgreSQL voice control-plane schema.
-- This migration is intentionally strict: an incompatible existing table must fail
-- instead of being silently accepted by CREATE TABLE IF NOT EXISTS.
-- Secrets, nonces, proofs, and TRTC user signatures are stored only as hashes or
-- application-encrypted bytea values. Raw audio and plaintext credentials never land here.

CREATE TABLE settings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key text NOT NULL UNIQUE,
    value_encrypted text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE device_credentials (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id varchar(64) NOT NULL UNIQUE,
    credential_id varchar(128) NOT NULL UNIQUE,
    device_name text NOT NULL,
    platform text NOT NULL,
    credential_hash text NOT NULL CHECK (
        position('$' in credential_hash) > 0
        AND length(split_part(credential_hash, '$', 1)) = 16
        AND length(split_part(credential_hash, '$', 2)) = 64
        AND split_part(credential_hash, '$', 1) ~ '^[0-9a-f]+$'
        AND split_part(credential_hash, '$', 2) ~ '^[0-9a-f]+$'
    ),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'revoked')),
    expires_at timestamptz NOT NULL,
    last_seen_at timestamptz,
    revoked_at timestamptz,
    revoke_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    CHECK ((status = 'revoked' AND revoked_at IS NOT NULL) OR status = 'active')
);
CREATE INDEX idx_device_credentials_status
    ON device_credentials(status, revoked_at);

CREATE TABLE pairing_codes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code_hash char(64) NOT NULL UNIQUE CHECK (length(code_hash) = 64),
    created_by_owner_id text NOT NULL,
    device_name_hint text,
    platform text NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    consumed_device_id varchar(64),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_pairing_codes_expiry
    ON pairing_codes(expires_at, consumed_at);

CREATE TABLE revoked_sessions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(128) NOT NULL UNIQUE,
    device_id varchar(64) NOT NULL,
    user_sig_fingerprint char(64) NOT NULL CHECK (length(user_sig_fingerprint) = 64),
    expires_at timestamptz NOT NULL,
    revoked_at timestamptz NOT NULL,
    reason text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_revoked_sessions_device
    ON revoked_sessions(device_id, expires_at);

CREATE TABLE session_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(128) NOT NULL,
    turn_id varchar(128),
    device_id varchar(64) NOT NULL,
    event_type text NOT NULL,
    state text,
    error_code text,
    metadata_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_session_events_lookup
    ON session_events(session_id, device_id, created_at DESC);

CREATE TABLE transcripts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(128) NOT NULL,
    ciphertext bytea NOT NULL,
    encryption_version text NOT NULL,
    started_at timestamptz NOT NULL,
    ended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_transcripts_session
    ON transcripts(session_id, created_at DESC);

CREATE TABLE privacy_audit_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action text NOT NULL,
    subject_type text NOT NULL,
    subject_id text NOT NULL,
    result text NOT NULL,
    metadata_redacted_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_privacy_audit_events_action
    ON privacy_audit_events(action, created_at DESC);

CREATE TABLE consumed_nonces (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id text NOT NULL,
    nonce_hash char(64) NOT NULL CHECK (length(nonce_hash) = 64),
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (subject_id, nonce_hash)
);
CREATE INDEX idx_consumed_nonces_expiry
    ON consumed_nonces(expires_at);

CREATE TABLE rate_limit_buckets (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id text NOT NULL,
    route_key text NOT NULL,
    window_start timestamptz NOT NULL,
    count integer NOT NULL DEFAULT 0 CHECK (count >= 0),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (subject_id, route_key, window_start)
);
CREATE INDEX idx_rate_limit_buckets_window
    ON rate_limit_buckets(window_start);

CREATE TABLE pending_session_claims (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id varchar(128) NOT NULL UNIQUE,
    device_id varchar(64) NOT NULL,
    room_id varchar(128) NOT NULL,
    generation integer NOT NULL CHECK (generation >= 0),
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    claim_token_hash char(64) UNIQUE CHECK (claim_token_hash IS NULL OR length(claim_token_hash) = 64),
    claimed_at timestamptz,
    signed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_pending_session_claims_available
    ON pending_session_claims(consumed_at, expires_at, created_at, id)
    WHERE claimed_at IS NULL;
CREATE INDEX idx_pending_session_claims_signing
    ON pending_session_claims(session_id, device_id, generation, claim_token_hash)
    WHERE claimed_at IS NOT NULL AND signed_at IS NULL;

CREATE TABLE control_plane_sessions (
    session_id varchar(128) PRIMARY KEY,
    device_id varchar(64) NOT NULL,
    room_id varchar(128) NOT NULL,
    generation integer NOT NULL CHECK (generation >= 0),
    state text NOT NULL DEFAULT 'ACTIVE' CHECK (
        state IN ('ACTIVE', 'TERMINATING', 'TERMINATED',
                  'TERMINATION_PARTIAL', 'TERMINATION_TIMEOUT', 'KWS_READY',
                  'SIGNING', 'ENTERING')
    ),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(session_id, generation)
);
CREATE INDEX idx_control_plane_sessions_device_state
    ON control_plane_sessions(device_id, state, generation);

CREATE TABLE control_plane_terminations (
    termination_id varchar(128) PRIMARY KEY,
    session_id varchar(128) NOT NULL,
    generation integer NOT NULL CHECK (generation >= 0),
    operation text NOT NULL CHECK (operation IN ('terminate', 'retry')),
    request_id varchar(256) NOT NULL,
    payload_hash char(64) NOT NULL CHECK (length(payload_hash) = 64),
    parent_termination_id varchar(128),
    result text NOT NULL DEFAULT 'pending' CHECK (result IN ('pending', 'complete', 'partial', 'timeout')),
    state text NOT NULL DEFAULT 'TERMINATING' CHECK (
        state IN ('TERMINATING', 'TERMINATED', 'TERMINATION_PARTIAL', 'TERMINATION_TIMEOUT')
    ),
    terminal_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (session_id) REFERENCES control_plane_sessions(session_id),
    FOREIGN KEY (parent_termination_id) REFERENCES control_plane_terminations(termination_id),
    UNIQUE(session_id, generation, request_id)
);
CREATE INDEX idx_control_plane_terminations_session_generation
    ON control_plane_terminations(session_id, generation, created_at DESC);
CREATE INDEX idx_control_plane_terminations_parent
    ON control_plane_terminations(parent_termination_id)
    WHERE parent_termination_id IS NOT NULL;

CREATE TABLE control_plane_acknowledgements (
    termination_id varchar(128) NOT NULL,
    acknowledgement text NOT NULL CHECK (
        acknowledgement IN ('android_trtc_left', 'sidecar_trtc_left', 'bridge_drained_closed',
                            'apm_cancelled_closed', 'brain_turns_sealed')
    ),
    result text NOT NULL CHECK (result IN ('pending', 'confirmed', 'failed')),
    inherited boolean NOT NULL DEFAULT false,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (termination_id, acknowledgement),
    FOREIGN KEY (termination_id) REFERENCES control_plane_terminations(termination_id) ON DELETE CASCADE
);

CREATE TABLE control_plane_ack_reports (
    termination_id varchar(128) NOT NULL,
    acknowledgement text NOT NULL,
    reporter text NOT NULL,
    result text NOT NULL CHECK (result IN ('confirmed', 'failed')),
    error_code text,
    reported_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (termination_id, acknowledgement, reporter),
    FOREIGN KEY (termination_id) REFERENCES control_plane_terminations(termination_id) ON DELETE CASCADE
);
CREATE INDEX idx_control_plane_ack_reports_pending
    ON control_plane_ack_reports(termination_id, acknowledgement, reported_at DESC);

CREATE TABLE control_plane_kws_readiness (
    session_id varchar(128) NOT NULL,
    generation integer NOT NULL CHECK (generation >= 0),
    reporter text NOT NULL,
    evidence_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    recorded_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (session_id, generation, reporter),
    FOREIGN KEY (session_id) REFERENCES control_plane_sessions(session_id)
);
CREATE INDEX idx_control_plane_kws_readiness_session
    ON control_plane_kws_readiness(session_id, generation, recorded_at);

CREATE TABLE control_plane_wake_events (
    wake_event_id varchar(128) NOT NULL,
    device_id varchar(64) NOT NULL,
    prior_session_id varchar(128) NOT NULL,
    prior_generation integer NOT NULL CHECK (prior_generation >= 0),
    new_session_id varchar(128) NOT NULL,
    new_generation integer NOT NULL CHECK (new_generation >= 0),
    payload_hash char(64) NOT NULL CHECK (length(payload_hash) = 64),
    record_json jsonb NOT NULL DEFAULT '{}'::jsonb,
    user_sig_ciphertext bytea NOT NULL,
    user_sig_encryption_version text NOT NULL,
    consumed_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (device_id, prior_session_id, prior_generation, wake_event_id),
    FOREIGN KEY (prior_session_id) REFERENCES control_plane_sessions(session_id),
    FOREIGN KEY (new_session_id) REFERENCES control_plane_sessions(session_id),
    CHECK (new_generation = prior_generation + 1)
);
CREATE INDEX idx_control_plane_wake_events_new_session
    ON control_plane_wake_events(new_session_id, new_generation);

CREATE TABLE control_plane_hello_proofs (
    jti varchar(128) PRIMARY KEY,
    nonce_hash char(64) NOT NULL UNIQUE CHECK (length(nonce_hash) = 64),
    proof_hash char(64) NOT NULL UNIQUE CHECK (length(proof_hash) = 64),
    session_id varchar(128) NOT NULL,
    device_id varchar(64) NOT NULL,
    room_id varchar(128) NOT NULL,
    sidecar_user_id varchar(64) NOT NULL,
    generation integer NOT NULL CHECK (generation >= 0),
    kid text NOT NULL,
    issuer text NOT NULL,
    audience text NOT NULL,
    protocol_version text NOT NULL,
    audio_format_json jsonb NOT NULL,
    issued_at timestamptz NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    FOREIGN KEY (session_id) REFERENCES control_plane_sessions(session_id),
    CHECK (expires_at > issued_at)
);
CREATE INDEX idx_hello_proofs_session_generation
    ON control_plane_hello_proofs(session_id, generation);
CREATE INDEX idx_hello_proofs_expiry
    ON control_plane_hello_proofs(expires_at, consumed_at);

-- The API owns these tables through a controlled service role. End-user roles are
-- explicitly denied access to hashes, encrypted signatures, sessions, and audit data.
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, authenticated;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, authenticated;
GRANT USAGE ON SCHEMA public TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO service_role;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO service_role;
