from __future__ import annotations

import re
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
MIGRATIONS_DIR = REPO_ROOT.parent / "cloudbase" / "migrations"
VERSIONED_MIGRATION = re.compile(r"^\d{14}_[a-z0-9_]+\.sql$")

EXPECTED_TABLES = {
    "settings",
    "device_credentials",
    "pairing_codes",
    "revoked_sessions",
    "session_events",
    "transcripts",
    "privacy_audit_events",
    "consumed_nonces",
    "rate_limit_buckets",
    "pending_session_claims",
    "control_plane_sessions",
    "control_plane_terminations",
    "control_plane_acknowledgements",
    "control_plane_ack_reports",
    "control_plane_kws_readiness",
    "control_plane_wake_events",
    "control_plane_hello_proofs",
}


def _migration_sql() -> str:
    files = sorted(MIGRATIONS_DIR.glob("*.sql"))
    assert files, "CloudBase PG migration directory must contain a versioned migration"
    assert all(VERSIONED_MIGRATION.fullmatch(path.name) for path in files)
    return "\n".join(path.read_text(encoding="utf-8") for path in files)


def test_voice_control_plane_schema_is_postgresql_and_complete() -> None:
    sql = _migration_sql()
    normalized = re.sub(r"\s+", " ", sql.lower())

    for table in EXPECTED_TABLES:
        assert re.search(rf"create table(?: if not exists)? {table}\b", normalized), table

    # PostgreSQL-native durable types and constraints; no SQLite/MySQL porting residue.
    assert "generated by default as identity" in normalized
    assert "timestamptz" in normalized
    assert "jsonb" in normalized
    assert "bytea" in normalized
    for forbidden in ("autoincrement", " begin immediate", " sqlite", " mysql", " real "):
        assert forbidden not in normalized, forbidden

    for required in (
        "credential_id",
        "claim_token_hash",
        "claimed_at",
        "signed_at",
        "generation",
        "foreign key (session_id) references control_plane_sessions",
        "on delete cascade",
        "unique (subject_id, nonce_hash)",
        "unique (subject_id, route_key, window_start)",
        "check (length(nonce_hash) = 64)",
        "check (length(proof_hash) = 64)",
    ):
        assert required in normalized, required


def test_voice_control_plane_schema_has_concurrency_indexes() -> None:
    sql = _migration_sql()
    normalized = re.sub(r"\s+", " ", sql.lower())
    for required_index in (
        "idx_pending_session_claims_available",
        "idx_hello_proofs_expiry",
        "idx_control_plane_sessions_device_state",
        "idx_control_plane_terminations_session_generation",
    ):
        assert required_index in normalized, required_index


def test_credential_hash_schema_accepts_salted_application_format() -> None:
    """The application stores ``salt$sha256``; the PG schema must not truncate it."""
    from app.voice.repositories.device_credentials import hash_secret

    stored = hash_secret("contract-secret")
    assert stored.count("$") == 1
    assert len(stored) > 64

    normalized = re.sub(r"\s+", " ", _migration_sql().lower())
    assert "credential_hash text not null" in normalized
    assert "credential_hash char(64)" not in normalized
    assert "position('$' in credential_hash) > 0" in normalized
    assert "length(split_part(credential_hash, '$', 1)) = 16" in normalized
    assert "length(split_part(credential_hash, '$', 2)) = 64" in normalized
